# Project information
site_name: Hermeto
repo_name: hermetoproject/hermeto
repo_url: https://github.com/hermetoproject/hermeto
edit_uri: edit/main/docs

# Theme configuration
theme:
  name: material
  locale: en
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.sections
    - search.share
    - search.suggest

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Navigation bar
nav:
  - Home: index.md
  - Usage: usage.md
  - Package managers:
      - bundler: bundler.md
      - cargo: cargo.md
      - generic: generic.md
      - gomod: gomod.md
      - npm: npm.md
      - pip: pip.md
      - rpm: rpm.md
      - yarn classic: yarn_classic.md
      - yarn berry: yarn.md

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Markdown validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

# Irrelevant files
exclude_docs: |
  dependency_confusion.md
  adr/
  design/
